import { Font } from 'fonteditor-core';
import type { IconGlyph, Project } from '@/types';
import { allocateCodepoints } from './codepoint-allocator';
import { buildSvgFont } from './svg-font-builder';
import { encodeGaspTable } from './gasp';
import { icomoonStyleMetrics } from './font-style';
import { forceOs2Version } from './ttf-postprocess';

export interface GeneratedFontData {
  ttfBuffer: ArrayBuffer;
  codepointMap: Map<string, number>;
}

/**
 * Generate a real TrueType font (glyf/loca outlines + gasp smoothing table)
 * from a list of icons. The font is produced by:
 *
 *  1. Allocating PUA codepoints for icons that don't already have one.
 *  2. Building an SVG-font XML document with each `<glyph>` carrying the
 *     Y-flipped, scaled path data.
 *  3. Parsing it through fonteditor-core, which converts SVG cubic Béziers
 *     into TrueType-compatible quadratic contours.
 *  4. Patching the TTFObject's `name` records and attaching a raw `gasp`
 *     table (visible to fonteditor-core's writer when `hinting: true`).
 *  5. Writing as `.ttf`, which goes through `glyf` / `loca` writers.
 *
 * Note: opentype.js is still used for *parsing* imported fonts in
 * src/lib/font-parsing/font-file-parser.ts. Do not uninstall it.
 */
export function generateFont(
  icons: IconGlyph[],
  project: Project
): GeneratedFontData {
  const codepointMap = allocateCodepoints(icons);

  const svgFont = buildSvgFont(icons, project, codepointMap);
  const font = Font.create(svgFont, { type: 'svg' });
  const ttf = font.get();

  // Force the icomoon style across vertical metrics, OS/2 layout, post
  // table, name records, and the .notdef glyph. This makes the output
  // byte-compatible (modulo icon-specific content) with the reference at
  // src/components/fonts/icomoon.ttf.
  const m = icomoonStyleMetrics(project.unitsPerEm);

  type Mutable = {
    hhea: Record<string, number>;
    'OS/2': Record<string, number>;
    post: Record<string, number>;
    name: Record<string, string>;
    glyf: Array<Record<string, unknown>>;
    gasp: Uint8Array;
  };
  const t = ttf as unknown as Mutable;

  // hhea — drop fonteditor-core's 812/-212/92 defaults.
  t.hhea.ascent = m.ascender;
  t.hhea.descent = m.descender;
  t.hhea.lineGap = 0;

  // OS/2 — version 3, USE_TYPO_METRICS only on fsSelection (clear reserved bit 7).
  t['OS/2'].version = 3;
  t['OS/2'].fsSelection = 0x0040;
  t['OS/2'].sTypoAscender = m.ascender;
  t['OS/2'].sTypoDescender = m.descender;
  t['OS/2'].sTypoLineGap = m.typoLineGap;
  t['OS/2'].usWinAscent = m.winAscent;
  t['OS/2'].usWinDescent = m.winDescent;

  // post — format 3.0 (no glyph-name table), zero underline metrics.
  t.post.format = 3;
  t.post.underlinePosition = 0;
  t.post.underlineThickness = 0;

  // name records (match icomoon's 7-field set).
  t.name = {
    ...t.name,
    fontFamily: project.fontFamily,
    fontSubFamily: 'Regular',
    uniqueSubFamily: project.fontFamily,
    fullName: project.fontFamily,
    version: 'Version 1.0',
    postScriptName: project.fontFamily,
    description: 'Font generated by Icon Font Generator',
  };

  // .notdef — empty (0 contours), full-em advance width, zero side bearing.
  t.glyf[0] = {
    contours: [],
    xMin: 0,
    yMin: 0,
    xMax: 0,
    yMax: 0,
    advanceWidth: project.unitsPerEm,
    leftSideBearing: 0,
    name: '.notdef',
    unicode: [],
  };

  // Attach raw gasp bytes. fonteditor-core's writer (ttfwriter.js prepareDump)
  // copies these verbatim when invoked with `hinting: true`.
  t.gasp = encodeGaspTable();

  font.set(ttf);

  const rawBuffer = font.write({
    type: 'ttf',
    hinting: true,
    toBuffer: false,
  }) as ArrayBuffer;

  // fonteditor-core's OS/2 writer forces version=4 regardless of what we set
  // on the TTFObject (see ttf-postprocess.ts for the long version). Patch
  // it to 3 in the output bytes and fix the affected checksums.
  const ttfBuffer = forceOs2Version(rawBuffer, 3);

  return { ttfBuffer, codepointMap };
}
